apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: praxis-demo

resources:
  - praxis-deployment.yaml
  - praxis-service.yaml
  - praxis-route.yaml
  - classifier-deployment.yaml
  - classifier-service.yaml

configMapGenerator:
  - name: praxis-config
    files:
      - config.yaml=praxis.yaml

generatorOptions:
  disableNameSuffixHash: false

labels:
  - pairs:
      app.kubernetes.io/part-of: praxis-llmd-demo
    includeSelectors: true
