apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: praxis-sr-demo

resources:
  - namespace.yaml
  - ../../base
  - vllm-cpu.yaml
  - vllm-gpu.yaml

patches:
  - path: route-hostname.yaml
